export Main from "./Main/index";
export Home from "./Home/index";
export Calc from "./Calc/index"
export MessageCenter from "./Message/index";
export MessageDetail from "./Message/Msglist/messageDetail";
export OrderList from "./Order/index";
export NoticeDetail from "./Message/Noticelist/noticeDetail";
export OrderDetail from "./Order/OrderDetail/orderDetail";
export Filldata from "./Filldata/index";
export Login from "./Login";
export FindPsd from './Findpsd/index';
export Mine from './Mine/Home/home';
export Myshop from './Mine/Myshop/myshop';
export Search from './Mine/Search/search';
export SearchDetail from './Mine/SearchDetail/searchDetail';
export ChangePsd from './Mine/ChangePsd/changePsd';
export Fillpeople from "./Filldata/FillPeople/fillPeople";
export Fillsame from "./Filldata/FillSame/fillSame";
export Fillother from "./Filldata/FillOther/fillOther";

export OrganNotice from "./OrganNotice/index"
export OneKey from "./OneKey/index"
export SetStages from "./SetStages/index"
export StageSuccess from "./StageSuccess/index"
export Receivables from "./Receivables/index"
export Goods from "./Goods/index"
export AddGood from "./AddGood/index"
